### ISSUE TITLE
Models convenience

### ISSUE THREAD

**Issue by krzysztofzablocki** [sanity-io/swift-sanity#10]
Hey,

I think the model object really should support things like:
- `Hashable`, `Equatable` conformances
- Read access to all properties
- explicit public initialisers

Otherwise I can't mock stuff up for testing, create transformation layers etc

**Comment by krzysztofzablocki** [comment]
@sgulseth can we conform to `Codable` not just `Decodable` ? otherwise I can't persist Image metadata and your API requires it for crops

**Comment by sgulseth** [comment]
Should be available in 0.4.0 for Image, Slug, and Ref
