### ISSUE TITLE
Feature request: Basic create document feature

### ISSUE THREAD

**Issue by eivindml** [sanity-io/swift-sanity#12]
Hi,

been using Sanity for a long time on the web. Currently working on a SwiftUI macOS project where I would love to experiment the `swift-sanity` client. But I would need some basic document creation functionality and the possibility to update a document, to be able to use it.

Thanks, looking forward to follow the project! 😊

**Comment by sgulseth** [comment]
Hi @eivindml! Sorry for the late reply here. We don't currently have it on our roadmap, as we were thinking that the iOs needs was more around fetching and displaying data. However, it shouldn't be very complicated to implement create{,OrReplace,ifNotExists} as documented here https://www.sanity.io/docs/http-mutations#95bb692d7fb0 

Can I ask what you need it for? :) Curious about what the needs are for apps

**Comment by eivindml** [comment]
Hi! 

I have previously made a tiny SwiftUI menubar app, that I can quickly drop screenshots etc onto, and it uploads the image to Sanity, and then copies the url to the clipboard. This was done directly with the api. 

Now I'm working on a native macOS and iOS time tracker app, and looking into if I should use Sanity for this, since I'm very familiar with it from all my web development. My other alternative is to use CoreData/CloudKit, but it's a bit more tricky to use.

So for this the use case would be to sync projects and tasks for each user through Sanity, and timer start timestamp etc.
