### ISSUE TITLE
swift package manager support

### ISSUE THREAD

**Issue by MadeByDouglas** [sanity-io/swift-sanity#22]
I'm unable to add this via swift package manager, it says it cannot resolve it. Is there something wrong or can this be added?
Also... is this project dead? I hope not, Sanity should support this.

**Comment by m0d9** [comment]
Same problem here, did you find a solution

**Comment by MadeByDouglas** [comment]
No not yet

**Comment by sgulseth** [comment]
Hi! Sorry for the late reply, I think I've isolated the issue with using an unstable SPM package. Can you try again by using version 0.12.0?

**Comment by MadeByDouglas** [comment]
Ok I just tried using SPM in Xcode 15 beta 2 with the default "up to next version" 0.12.0 and it works! Looks like it imports Sanity and SanityClient works and all that so looks good
